# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5229766bbeb8872471ae13d9d9e688e9fe526e881bd276bb94f1703ac9a5953b26de1473daabe384588199b145074ab842db5efbd55a38fc2cb38b8989063f0

test:
  secret_key_base: be9ebdd826c462e59d95a8278fad50d449a88ff69c15f38ccc37baa2f9fe72c10b98041ce101e4559fcb9546b1a36f46eca2f1679d242b13ad0deb6d24459f79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
